ARDUINO_DIR   = /Applications/Arduino.app/Contents/Resources/Java
USER_LIB_PATH = ./libraries
OBJDIR        = ./.build-$(BOARD_TAG)
ARDUINO_LIBS  = I2CDev MPU6050

BOARD_TAG         = mega2560
MONITOR_BAUDRATE  = 115200
MONITOR_PORT      = /dev/tty.usbmodem*
AVRDDUDE          = /usr/local/bin/avrdude

include ~/hardware/Arduino-Makefile/Arduino.mk
